# Generated by Django 5.0.14 on 2026-10-08 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Instrumento')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('categoria', models.CharField(choices=[('Cuerda', 'Cuerda'), ('Viento', 'Viento'), ('Percusión', 'Percusión'), ('Teclado', 'Teclado'), ('Electrónico', 'Electrónico')], max_length=20, verbose_name='Categoría')),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El precio debe ser mayor a 0')], verbose_name='Precio ($)')),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='El stock no puede ser negativo')], verbose_name='Stock disponible')),
                ('anio_fabricacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1800, message='Año no válido'), django.core.validators.MaxValueValidator(2026, message='El año no puede ser superior al actual')], verbose_name='Año de Fabricación')),
                ('imagen_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80', null=True, verbose_name='URL de Imagen (Opcional)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
    ]
