# Generated by Django 5.0.14 on 2026-10-08 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='imagen_url',
        ),
    ]
